import { PortalExperiencePage } from "./types";

export const INITIAL_PORTAL_PAGES: PortalExperiencePage[] = [
  {
    id: "page-01",
    pageId: "PG-027-P01",
    name: "Discovery Scheduled Dashboard",
    slug: "discovery-scheduled-dashboard",
    route: "/portal/discovery",
    category: "Discovery & Pre-Sale",
    description: "Pre-sale portal home showing upcoming Discovery Call countdown, meeting details, and locked workspace teasers.",
    status: "published",
    associatedStageId: "stage-02",
    associatedStageName: "02 · Discovery Call Scheduled",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-02",
    pageId: "PG-027-P02",
    name: "Discovery Call Details",
    slug: "discovery-call-details",
    route: "/portal/discovery-call",
    category: "Discovery & Pre-Sale",
    description: "Detailed video link, coach bio, preparation checklist, and appointment rescheduling options.",
    status: "published",
    associatedStageId: "stage-02",
    associatedStageName: "02 · Discovery Call Scheduled",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-03",
    pageId: "PG-027-P03",
    name: "Getting Started",
    slug: "getting-started",
    route: "/portal/getting-started",
    category: "Discovery & Pre-Sale",
    description: "Overview of Waypoint's 4-pillar IEP advocacy methodology and what parents need for their initial consultation.",
    status: "published",
    associatedStageId: "stage-01",
    associatedStageName: "01 · Discovery Inquiry Submitted",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-04",
    pageId: "PG-027-P04",
    name: "Student Selection",
    slug: "student-selection",
    route: "/portal/student-selection",
    category: "Onboarding & Setup",
    description: "Interactive card selector for 1, 2, or 3+ students with sibling discount calculations.",
    status: "published",
    associatedStageId: "stage-04",
    associatedStageName: "04 · Select Number of Students",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-05",
    pageId: "PG-027-P05",
    name: "Support Selection",
    slug: "support-selection",
    route: "/portal/support-selection",
    category: "Onboarding & Setup",
    description: "Tier comparison matrix (Full IEP Representation, Document Review & Strategy, or Retainer).",
    status: "published",
    associatedStageId: "stage-05",
    associatedStageName: "05 · Select Support Level",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-06",
    pageId: "PG-027-P06",
    name: "Checkout",
    slug: "checkout",
    route: "/portal/checkout",
    category: "Account & Billing",
    description: "Stripe-powered PCI-compliant payment portal with payment plan selector and immediate receipt generation.",
    status: "published",
    associatedStageId: "stage-06",
    associatedStageName: "06 · Checkout / Payment",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-07",
    pageId: "PG-027-P07",
    name: "Welcome to Waypoint",
    slug: "welcome-to-waypoint",
    route: "/portal/welcome",
    category: "Onboarding & Setup",
    description: "Post-purchase welcome screen featuring Byron's onboarding video and progressive step map.",
    status: "published",
    associatedStageId: "stage-07",
    associatedStageName: "07 · Welcome to Waypoint",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-08",
    pageId: "PG-027-P08",
    name: "Advocacy Agreement",
    slug: "advocacy-agreement",
    route: "/portal/agreements",
    category: "Onboarding & Setup",
    description: "Legal representation terms, FERPA disclosure, and digital signature pad.",
    status: "published",
    associatedStageId: "stage-08",
    associatedStageName: "08 · Advocacy Agreements",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-09",
    pageId: "PG-027-P09",
    name: "Parent / Guardian Setup",
    slug: "parent-guardian-setup",
    route: "/portal/parent-setup",
    category: "Onboarding & Setup",
    description: "Primary and secondary parent contacts, phone preferences, emergency contacts, and notifications.",
    status: "published",
    associatedStageId: "stage-09",
    associatedStageName: "09 · Student Setup",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-10",
    pageId: "PG-027-P10",
    name: "Student Setup",
    slug: "student-setup",
    route: "/portal/student-setup",
    category: "Onboarding & Setup",
    description: "Student demographics, school district, current teacher names, and special education eligibility category.",
    status: "published",
    associatedStageId: "stage-09",
    associatedStageName: "09 · Student Setup",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-11",
    pageId: "PG-027-P11",
    name: "Document Upload",
    slug: "document-upload",
    route: "/portal/document-upload",
    category: "Onboarding & Setup",
    description: "Categorized file dropzones for IEPs, 504s, psychological evals, medical records, and school emails.",
    status: "published",
    associatedStageId: "stage-10",
    associatedStageName: "10 · Records & Document Upload",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-12",
    pageId: "PG-027-P12",
    name: "Advocacy Intake",
    slug: "advocacy-intake",
    route: "/portal/advocacy-intake",
    category: "Onboarding & Setup",
    description: "Multi-field IEP priority questionnaire with voice input, autosave, and parent concern categorizer.",
    status: "published",
    associatedStageId: "stage-11",
    associatedStageName: "11 · Advocacy Intake",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-13",
    pageId: "PG-027-P13",
    name: "Onboarding Checklist",
    slug: "onboarding-checklist",
    route: "/portal/onboarding-complete",
    category: "Onboarding & Setup",
    description: "Progressive onboarding step validator showing completed checkmarks and launching the strategy session booking.",
    status: "published",
    associatedStageId: "stage-12",
    associatedStageName: "12 · Onboarding Complete",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-14",
    pageId: "PG-027-P14",
    name: "Client Dashboard",
    slug: "client-dashboard",
    route: "/portal/dashboard",
    category: "Active Workspaces",
    description: "Primary client command center featuring Case Compass status, countdown to IEP meeting, and recent alerts.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-15",
    pageId: "PG-027-P15",
    name: "Student Workspace",
    slug: "student-workspace",
    route: "/portal/student-workspace",
    category: "Active Workspaces",
    description: "Per-student deep dive with IEP goals, accommodations tracker, service hours tally, and school roster.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-16",
    pageId: "PG-027-P16",
    name: "Case Workspace",
    slug: "case-workspace",
    route: "/portal/case-workspace",
    category: "Active Workspaces",
    description: "Active advocacy dispute / strategy board with chronological milestones and action roadmaps.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-17",
    pageId: "PG-027-P17",
    name: "Meetings",
    slug: "meetings",
    route: "/portal/meetings",
    category: "Active Workspaces",
    description: "Upcoming IEP meetings, pre-meeting strategy agenda, audio recording uploads, and meeting debrief notes.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-18",
    pageId: "PG-027-P18",
    name: "Documents",
    slug: "documents",
    route: "/portal/documents",
    category: "Active Workspaces",
    description: "Complete Cloudflare R2 document vault with IEP Comparator, OCR search, and secure file downloads.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-19",
    pageId: "PG-027-P19",
    name: "Requests",
    slug: "requests",
    route: "/portal/requests",
    category: "Active Workspaces",
    description: "Formal letter builder for IEE (Independent Educational Evaluation), Records Requests, and PWN demands.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-20",
    pageId: "PG-027-P20",
    name: "Billing",
    slug: "billing",
    route: "/portal/billing",
    category: "Account & Billing",
    description: "Household invoices, payment history receipts, active retainer balances, and card on file management.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-21",
    pageId: "PG-027-P21",
    name: "Account Settings",
    slug: "account-settings",
    route: "/portal/settings",
    category: "Account & Billing",
    description: "Clerk user profile settings, password management, SMS notification toggles, and authorized family members.",
    status: "published",
    associatedStageId: "stage-13",
    associatedStageName: "13 · Active Advocacy",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-22",
    pageId: "PG-027-P22",
    name: "Closing Experience",
    slug: "closing-experience",
    route: "/portal/closing",
    category: "Lifecycle & Offboarding",
    description: "Post-advocacy wrap up, permanent record export ZIP generator, satisfaction survey, and alumni renewal options.",
    status: "published",
    associatedStageId: "stage-14",
    associatedStageName: "14 · Closing / Inactive Client",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  },
  {
    id: "page-23",
    pageId: "PG-027-P23",
    name: "Advocacy Plan Renewal & Extension",
    slug: "advocacy-renewal",
    route: "/portal/renewal",
    category: "Retention & Renewal",
    description: "Annual IEP representation renewal hub, retainer replenishment selector, multi-student discounts, add-on riders, and instant renewal checkout.",
    status: "published",
    associatedStageId: "stage-15",
    associatedStageName: "15 · Annual Advocacy Renewal & Listing",
    lastEditedBy: "Byron Honea",
    isInteractivePreviewReady: true
  }
];
