import { eq, and, desc, sql } from "drizzle-orm";
import { advocateTimeEntries, contacts, users } from "../../drizzle/schema";
import { getDb } from "./connection";

export interface LogTimeEntryInput {
  userId: number;
  familyContactId?: number;
  studentContactId?: number;
  workType: string;
  entryDate: string; // YYYY-MM-DD
  startTime?: string;
  endTime?: string;
  durationMinutes: number;
  relatedRecordType?: string;
  relatedRecordId?: string;
  planTierAtTime?: string;
  notes?: string;
  isAutoGenerated?: boolean;
}

/**
 * Logs a manual or completed timer entry into advocate_time_entries.
 */
export async function logTimeEntry(input: LogTimeEntryInput) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  // If student is provided, resolve plan tier at this moment
  let planTier = input.planTierAtTime || "$55";
  let familyId = input.familyContactId;

  if (input.studentContactId && (!input.planTierAtTime || !familyId)) {
    const studentRow = await db
      .select({
        planTier: contacts.planTier,
        parentContactId: contacts.parentContactId,
      })
      .from(contacts)
      .where(eq(contacts.id, input.studentContactId))
      .limit(1);

    if (studentRow[0]) {
      if (!input.planTierAtTime && studentRow[0].planTier) {
        planTier = studentRow[0].planTier;
      }
      if (!familyId && studentRow[0].parentContactId) {
        familyId = studentRow[0].parentContactId;
      }
    }
  }

  const result = await db.insert(advocateTimeEntries).values({
    tenantId: "waypoint",
    userId: input.userId,
    familyContactId: familyId || input.studentContactId || null,
    studentContactId: input.studentContactId || null,
    workType: input.workType,
    entryDate: input.entryDate,
    startTime: input.startTime || null,
    endTime: input.endTime || null,
    durationMinutes: Math.max(1, input.durationMinutes),
    relatedRecordType: input.relatedRecordType || null,
    relatedRecordId: input.relatedRecordId || null,
    planTierAtTime: planTier,
    notes: input.notes || null,
    isAutoGenerated: input.isAutoGenerated ?? false,
    isTimerRunning: false,
    timerStartedAt: null,
  });

  return { success: true, result };
}

/**
 * Starts an active live timer for an advocate.
 */
export async function startLiveTimer(input: {
  userId: number;
  workType: string;
  studentContactId?: number;
  relatedRecordType?: string;
  relatedRecordId?: string;
  notes?: string;
}) {
  const db = await getDb();
  if (!db) throw new Error("Database not available");

  // First stop any previously running timers for this user
  await stopActiveTimer(input.userId);

  const today = new Date().toISOString().split("T")[0];

  const result = await db.insert(advocateTimeEntries).values({
    tenantId: "waypoint",
    userId: input.userId,
    studentContactId: input.studentContactId || null,
    workType: input.workType,
    entryDate: today,
    durationMinutes: 0,
    relatedRecordType: input.relatedRecordType || null,
    relatedRecordId: input.relatedRecordId || null,
    notes: input.notes || null,
    isTimerRunning: true,
    timerStartedAt: new Date(),
  });

  return { success: true, timerStartedAt: new Date() };
}

/**
 * Stops any currently running timer for the user and computes total duration.
 */
export async function stopActiveTimer(userId: number, notes?: string) {
  const db = await getDb();
  if (!db) return null;

  const running = await db
    .select()
    .from(advocateTimeEntries)
    .where(
      and(
        eq(advocateTimeEntries.userId, userId),
        eq(advocateTimeEntries.isTimerRunning, true)
      )
    )
    .limit(1);

  if (running.length === 0) return null;

  const entry = running[0];
  const startTime = entry.timerStartedAt ? new Date(entry.timerStartedAt).getTime() : Date.now();
  const elapsedMinutes = Math.max(1, Math.round((Date.now() - startTime) / 60000));

  await db
    .update(advocateTimeEntries)
    .set({
      isTimerRunning: false,
      durationMinutes: elapsedMinutes,
      notes: notes ? (entry.notes ? `${entry.notes} — ${notes}` : notes) : entry.notes,
      updatedAt: new Date(),
    })
    .where(eq(advocateTimeEntries.id, entry.id));

  return { id: entry.id, durationMinutes: elapsedMinutes };
}

/**
 * Gets the current active running timer for an advocate (if any).
 */
export async function getActiveTimer(userId: number) {
  const db = await getDb();
  if (!db) return null;

  const running = await db
    .select()
    .from(advocateTimeEntries)
    .where(
      and(
        eq(advocateTimeEntries.userId, userId),
        eq(advocateTimeEntries.isTimerRunning, true)
      )
    )
    .limit(1);

  if (running.length === 0) return null;

  const entry = running[0];
  let studentName: string | null = null;

  if (entry.studentContactId) {
    const st = await db
      .select({ firstName: contacts.firstName, lastName: contacts.lastName })
      .from(contacts)
      .where(eq(contacts.id, entry.studentContactId))
      .limit(1);
    if (st[0]) {
      studentName = `${st[0].firstName} ${st[0].lastName}`.trim();
    }
  }

  return {
    ...entry,
    studentName,
  };
}

/**
 * Lists recent time entries with optional filters.
 */
export async function getTimeEntries(filters?: {
  userId?: number;
  studentContactId?: number;
  limit?: number;
}) {
  const db = await getDb();
  if (!db) return [];

  const limit = filters?.limit || 50;

  const entries = await db
    .select({
      id: advocateTimeEntries.id,
      userId: advocateTimeEntries.userId,
      workType: advocateTimeEntries.workType,
      entryDate: advocateTimeEntries.entryDate,
      durationMinutes: advocateTimeEntries.durationMinutes,
      planTierAtTime: advocateTimeEntries.planTierAtTime,
      notes: advocateTimeEntries.notes,
      studentContactId: advocateTimeEntries.studentContactId,
      createdAt: advocateTimeEntries.createdAt,
    })
    .from(advocateTimeEntries)
    .where(eq(advocateTimeEntries.isTimerRunning, false))
    .orderBy(desc(advocateTimeEntries.createdAt))
    .limit(limit);

  return entries;
}
